#!/bin/sh
set -eu

chmod 0755 /usr/local/sbin/community-repo-ui /usr/local/etc/rc.d/community_repo_ui
chmod 0644 /usr/local/www/pkg_mgr_community.php \
	/usr/local/share/pfSense-pkg-community-repo/community_repo.inc \
	/usr/local/share/pfSense-pkg-community-repo/info.xml \
	/usr/local/pkg/community_repo.xml

mkdir -p /usr/local/etc/pkg/repos
/usr/local/bin/php -r '
require_once("/usr/local/share/pfSense-pkg-community-repo/community_repo.inc");
$enabled = !file_exists(COMMUNITY_REPO_CONF) || community_repo_enabled();
exit(community_repo_write_config($enabled) ? 0 : 1);
'

/usr/local/sbin/community-repo-ui --apply

php <<'PHP'
<?php
require_once('/etc/inc/config.inc');
require_once('/etc/inc/pkg-utils.inc');
$menus = config_get_path('installedpackages/menu', []);
if (is_array($menus)) {
	$menus = array_values(array_filter($menus, function ($entry) {
		return !is_array($entry) || ($entry['url'] ?? '') !== '/pkg_mgr_community.php';
	}));
	config_set_path('installedpackages/menu', $menus);
}
if (!install_package_xml('community-repo')) {
	fwrite(STDERR, "Unable to register community repository package metadata.\n");
	exit(1);
}
PHP

exit 0
